# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: mavendep

on:
  push:
    branches: [main, release]

jobs:
    publish:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#           MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: run tests
        run : mvn test
#       - if: github.event.release
      - name: Update version in pom.xml 
        run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 versions:commit
#         run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
            maven_profiles: deploy, verify
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
            nexus_username: ${{ secrets.OSSRH_USERNAME }}
            nexus_password: ${{ secrets.OSSRH_TOKEN }}
