# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: mavendep

on:
  push:
    branches: [main, release]

jobs:
    publish:
      runs-on: windows-latest
      steps:
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Set up GPG
          run: |
            echo "$GPG_PRIVATE_KEY" > private.asc
            gpg --import --batch private.asc
          env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        - name: Deploy
          id: deploy
          run: |
            mvn -B -Pdeploy -Dgpg.passphrase=${GPG_PASSPHRASE} clean deploy
            echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
